include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/deno.yml"

vet:
  tags:
    - jmccown-user
    - shell-exe
semantic-releaser:
  stage: .post
  tags:
    - jmccown-user
  script:
    - npx semantic-release
    - shell-exe
