include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/core.yml"
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/meta.yml"
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/deno.yml"

semantic-releaser:
  stage: .post
  tags:
    - jmccown-user
  script:
    - npx semantic-release
