include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/deno.yml"

vet:
  tags:
    - jmccown-user
    - shell-exe
  script:
    - deno lint mod.ts cli.ts

semantic-releaser:
  stage: .post
  tags:
    - jmccown-user
    - shell-exe
  script:
    - echo "Too broken at the moment, it could probably run in its own docker image with all semantic release plugins needed pre installed, but running locally is easier"
    - exit 1
    - semantic-release
