include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/deno.yml"

variables:
  JM_DENO_FILES: mod.ts cli.ts

semantic-releaser:
  stage: .post
  tags:
    - jmccown-user
    - shell-exe
  script:
    - echo "$PATH"
    - semantic-release
    - cd dist-npm
    - npm publish
  artifacts:
    when: on_failure
    untracked: true
    paths:
      - dist-npm
