include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/deno.yml"

vet:
  tags:
    - jmccown-user
    - shell-exe
  script:
    - deno lint mod.ts cli.ts

semantic-releaser:
  stage: .post
  tags:
    - jmccown-user
    - shell-exe
  script:
    - echo "$PATH"
    - semantic-release
    - ls
    - npm --prefix dist-npm publish
